grammar = {
'Keywords': [['Keyword'], ['Keyword', 'Keywords'], ['']],
'Keyword': [['int'], ['float'], ['char'], ['if'], ['else if'], ['else'], ['while'], ['for'], ['return']],

'Strings': [['DoubleQuoteString'], ['SingleQuoteString']],
'DoubleQuoteString': [['"', "DoubleQuoteContent", '"']],
'SingleQuoteString': [["'", "SingleQuoteContent", "'"]],
'DoubleQuoteContent': [["NonQuoteCharacters"], ["EscapeCharacter"], ["DoubleQuoteString"]],
'SingleQuoteContent': [["NonQuoteCharacters"], ["EscapeCharacter"], ["SingleQuoteString"]],
'NonQuoteCharacter': [["Letter"], ["Digits"], ["SpecialSymbol"], ["Punctuator"]],
'NonQuoteCharacters': [["NonQuoteCharacter", "NonQuoteCharacters"], ['']],
'EscapeCharacter': [["\\"], ["\\n"], ["\\t"], ['\\"'], ["\\'"]],

'Identifiers': [['Identifier'], ['Identifier', 'Identifiers'], ['']],
'Identifier': [["Letters", "Anotherletter"], ["_", "Anotherletter"]],
'Anotherletter': [[''], ["Character", "Anotherletter"]],
'Character': [["Letters"], ["Digit"], ["_"]],
'Letters': [['a'], ['b'], ['c'], ['d'], ['e'], ['f'], ['g'], ['h'], ['i'], ['j'], ['k'], ['l'], ['m'], ['n'], ['o'], ['p'], ['q'], ['r'], ['s'], ['t'], ['u'], ['v'], ['w'], ['x'], ['y'], ['z'], ['A'], ['B'], ['C'], ['D'], ['E'], ['F'], ['G'], ['H'], ['I'], ['J'], ['K'], ['L'], ['M'], ['N'], ['O'], ['P'], ['Q'], ['R'], ['S'], ['T'], ['U'], ['V'], ['W'], ['X'], ['Y'], ['Z']],
'SpecialSymbol': [['!'], ['@'], ['£'], ['#'], ['$'], ['^'], ['&'], ['*'], ['+'], ['-'], ['_'], ['='], ['<'], ['>'], ['?']],
'Punctuator': [['('], [')'], ['{'], ['}'], ['['], [']'], ['.'], [','], [';']],

'Program': [['Type', 'Funcname', '(', 'Arglist', ')', '{', 'Statements', '}']],
'Type': [['void'], ['int'], ['float'], ['double'], ['char']],
'Funcname': [['main'], ['Identifier']],
'Arglist': [['Identifier'], ['Type', 'Identifier'], ['']],
'Arglists': [['Arglist'], ['Arglist', 'Arglists'], ['']],
'Statements': [['Statement'], ['Statement', 'Statements'], ['']],
'Statement': [['Variabledec'], ['Ifstatement'], ['Whileloop'], ['Forloop'], ['Expression'], ['Returnstatement']],
'Variabledec': [['Type', 'Assignmentexp']],
'Expression': [['Assignmentexp'], ['Logicalexp'], ['Equalityexp'], ['Arithmeticexp'], ['Relationalexp']],
'Ifstatement': [['if', '(', 'Expression', ')', '{', 'Statements', '}'], 
               ['if', '(', 'Expression', ')', '{', 'Statements', '}', 'else', '{', 'Statements', '}'], 
               ['if', '(', 'Expression', ')', '{', 'Statements', '}', 'Elseifstatements', 'else', '{', 'Statements', '}']],
'Elseifstatements': [['Elseifstatement'], ['Elseifstatement', 'Elseifstatements'], ['']],
'Elseifstatement': [['else', 'if', '(', 'Expression', ')', '{', 'Statements', '}']],
'Forloop': [['for', '(', 'Expression', ';', 'Expression', ';', 'Expression', ')', '{', 'Statements', '}']],
'Whileloop': [['while', '(', 'Expression', ')', '{', 'Statements', '}']],
'Returnstatement': [['return', 'Expression']],

'Number': [['Integer'], ['Float']],
'Integer': [['Sign', 'Digits'], ['Digits']],
'Sign': [["+"], ["-"]],
'Digits': [['Digit',], ['Digit', 'Digits'], ['']],
'Digit': [['Zero'], ['Onetonine']],
'Zero': [['0']],
'Onetonine': [['1'], ['2'], ['3'], ['4'], ['5'], ['6'], ['7'], ['8'], ['9']],
'Float': [['Sign', 'Digits', '.', 'Digits'], ['Digits', '.', 'Digits']],

'Assignmentexp': [['Identifier', '=', 'Expression']],
'Logicalexp': [['Expression', 'LogicalOp', 'Expression']],
'LogicalOp': [['&&'], ['||']],
'Relationalexp': [['Expression', 'RelationalOp', 'Expression']],
'RelationalOp': [['<'], ['>'], ['<='], ['>=']],
'Equalityexp': [['Expression', 'EqualityOp', 'Expression']],
'EqualityOp': [['=='], ['!=']],
'Arithmeticexp': [['Term'],['Arithmeticexp', 'ArithmeticOp', 'Term'], ['Term', 'IncrementalOp']],
'ArithmeticOp': [['+'], ['-'], ['*'], ['/'], ['^'], ['%']],
'IncrementalOp': [['++'], ['--']],
'Term': [['Factor'],['Term', '*', 'Factor'],['Term', '/', 'Factor']],
'Factor': [['Digit'],['Identifier'],['(', 'Arithmeticexp', ')']],

}
